[supervisord]
nodaemon=true

[program:redis]
command=/usr/bin/redis-server
autorestart=true

[program:init]
command=/etc/init.sh
autorestart=false
startsecs=0

[program:rspamd]
command=/bin/sh -c "sleep 10 && /usr/bin/rspamd -f --insecure"
autorestart=true

[program:dovecot]
command=/bin/sh -c "sleep 15 && /usr/sbin/dovecot -F"
autorestart=true

[program:postfix]
command=/bin/sh -c "sleep 30 && /usr/sbin/postfix start-fg"
autorestart=true
