[supervisord]
nodaemon=true

[program:redis]
command=/usr/bin/redis-server
autorestart=true
priority=1

[program:init]
command=/etc/init.sh
autorestart=false
startsecs=0
priority=2

[program:opendkim]
command=/bin/sh -c "sleep 5 && /usr/sbin/opendkim -f -x /etc/opendkim.conf"
autorestart=true
priority=3

[program:postfix]
command=/usr/sbin/postfix start-fg
autorestart=true
priority=4

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
priority=4

[program:rspamd]
command=/usr/bin/rspamd -f --insecure
autorestart=true
priority=4
