[supervisord]
nodaemon=true

[program:redis]
command=/usr/bin/redis-server
autorestart=true

[program:postfix]
command=/usr/sbin/postfix start-fg
autorestart=true

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true

[program:rspamd]
command=/usr/bin/rspamd -f --insecure
autorestart=true

[program:opendkim]
command=/bin/sh -c "sleep 2 && /usr/sbin/opendkim -f -x /etc/opendkim.conf"
autorestart=true
