Domain                  cargo-port.eu
KeyFile                 /etc/opendkim/keys/cargo-port.eu/mail.private
Selector                mail
Socket                  inet:8891@localhost
UserID                  opendkim
